### ISSUE TITLE
Android plugin pops up invalid URL dialog

### ISSUE THREAD

**Issue by mdkhanga** [magnetsystems/rest2mobile#16]
Even though the URL is valid.

I enter a url and hit the test button, It will pop up the error but successfully call the URL

**Comment by etexier** [comment]
Can you give me the URL you used?

**Comment by mdkhanga** [comment]
The url I entered was 
http://localhost:8080/rest/admin/logging/properties
http://localhost:8080/rest/controllers.json

**Comment by etexier** [comment]
I created https://github.com/magnetsystems/r2m-plugin-android/issues/1 to track it
