### ISSUE TITLE
Obtaining the twitter OAuth token using the Android SDK and plugin-generated classes failed

### ISSUE THREAD

**Issue by skwokmag** [magnetsystems/rest2mobile#17]
<b>To reproduce</b>
1. Inside Android Studio, use the Magnet plugin to generate the classes for obtaining the OAuth bearer token following the instructions given on https://dev.twitter.com/oauth/application-only. The api is: oauth2/token
2. Inside the app, call the controller using the following codes:

<pre>
      final String E_TOKEN_TYPE = "bearer";
      final String AUTH = "Basic  encoded_bearer_token_credentials";
      final String CONTENT_TYPE = "application/x-www-form-urlencoded;charset=utf-8";
      final String GRANT_TYPE = "client_credentials";

      TwitterTokenControllerFactory twitterTokenControllerFactory = new TwitterTokenControllerFactory(magnetClient);
      TwitterTokenController tokenController = twitterTokenControllerFactory.obtainInstance();

      Call<TwitterTokenResult> resultCall = tokenController.twitterToken(GRANT_TYPE, AUTH, CONTENT_TYPE,null);
      TwitterTokenResult twitterTokenResult = resultCall.get();
</pre>

<b>Expected Result</b>
1. The call will execute successfully.
2. One may call twitterTokenResult.getAccess_token() to obtain the token.

<b>Result</b>
The call, twitterToken, threw com.magnet.android.mms.exception.AuthenticationException

<b>Cause</b>
The Twitter api is expected to return the token and the type of it in a JSON object; however, that particular call is returning "401" if one submits the http header "Accept=application/json", which is what the Android SDK is doing. Any other values for the Accept header seem to work. This is fairly strange.

<b>Solution</b>
Magnet Systems will change its SDK and will provide a new release very soon.

**Comment by etexier** [comment]
This is fixed now using the android sdk 1.1.0
