### ISSUE TITLE
Too disconnected from server side

### ISSUE THREAD

**Issue by mdkhanga** [magnetsystems/rest2mobile#19]
I have used the rest2mobile plugin to generate client code for android and I must say it works well. Kudos to the team.

I am a full stack developer in that I develop both android app and any server side code - Servlets, Guice, Spring and other types of server side components.

My concern is that I have to use 2 separate environment - r2m for client side and something else for serverside.

Even in the old J2EE days - which is 15 year old, we had integrated IDEs that let you do client side and server side coding in the same IDE.

Keep up the good work.

**Comment by etexier** [comment]
Thanks for you comments. We have received similar feedback asking us to support mobile back-end development as well.
We are investigating it, but for the moment, rest2mobile tool suite is focused on simplifying mobile-side development and supporting the same experience for Android, iOS and Javascript. The fact that it is  server-agnostic makes it easier to adopt.

If you are a full stack engineer wanting to use Android Studio for both front and back-end development, you could give [Google App Engine](https://cloud.google.com/appengine/docs) a try.
