### ISSUE TITLE
No longer working on 6.3.1 Xcode

### ISSUE THREAD

**Issue by kilabyte** [magnetsystems/rest2mobile#22]
Plugin no longer working in latest Xcode build

**Comment by priteshshah1983** [comment]
Are you using the latest release? https://github.com/magnetsystems/r2m-plugin-ios/releases/download/v1.1.3/r2m-Xcode-plugin.zip

**Comment by kilabyte** [comment]
The link you provided works. You should perhaps update your developer website with that link. thanks!

**Comment by priteshshah1983** [comment]
Thanks for pointing it out! I will update the developer website.
